FROM node:20

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

# COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api-server/package*.json ./

RUN pnpm install

# COPY apps ./apps
# COPY packages ./packages
# COPY tools ./tools
# COPY tsconfig.json ./

# Now copy the rest of your source code (excluding node_modules because of .dockerignore)
COPY apps/worker .

# Default command, can override later
CMD ["pnpm", "--filter", "api-server", "run", "worker:buyTicket"]
