version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /app/apps/api-server      
    command: ["pnpm", "run", "dev", "--filter", "api-server"]
    volumes:
      - .:/app    
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development

  worker-buy-ticket:
    build:
      context: .
      dockerfile: Dockerfile.worker
    working_dir: /app/apps/worker   
    command: ["pnpm", "run", "worker:buyTicket"]
    volumes:
      - .:/app    
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development      

  worker-release-reservation:
    build:
      context: .
      dockerfile: Dockerfile.worker
    working_dir: /app/apps/worker
    command: ["pnpm", "run", "worker:releaseReservation"] 
    volumes:
      - .:/app       
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development      
